### ISSUE TITLE
Error: unknown option `--address-space'

### ISSUE THREAD

**Issue by chrissom** [weaveworks-guides/weave-kubernetes-coreos-azure#7]
Hi,

During `./create-kubernetes-cluster.js` I got this error:

```
error: unknown option `--address-space'
azure_wrapper/fail: Exiting due to an error.
```

Any idea how to manage that?

More info:
- node: v6.6.0
- npm: 3.10.8
- azure-cli: 0.10.5

**Comment by cooktheryan** [comment]
Copied from another post 

This occurs when you've switched to the Resource Manager deployment model. Switch back to Service Management:

azure config mode asm

**Comment by errordeveloper** [comment]
I am closing this issue as I am going to archive this repo.
